package pages;

public class SalesSQL {
	static String mySQL = "";
	
	public static String getSalesSQL(String date){
		mySQL = "BEGIN\n "
			+"DECLARE @FROM_DATE CHAR(8);\n "		
			+"DECLARE @TO_DATE CHAR(8);\n "
			+"DECLARE @KIJUN_DATE char(8);\n "
			+"DECLARE @AT_CAR_KUBUN VARCHAR(10);\n "
			+"		\n "
			+"	\n "
			+"	SET @KIJUN_DATE   = '"+date+"'\n "
			+"SET @AT_CAR_KUBUN = 'a271'\n "
			+"SET @TO_DATE   = @KIJUN_DATE\n "
			+"SET @FROM_DATE = SUBSTRING(@KIJUN_DATE, 1, 6) + '01'\n "
			+"	\n "
			+"	\n "
			+"	PRINT @TO_DATE\n "
			+"	PRINT @FROM_DATE\n "
			+"	\n "
			+"	\n "
			+"	\n "
			+"	SELECT \n "
			   +"KIJUN_DATE = KIJUN_DATE \n "
			 +", DEALER = REPLACE(REPLACE(DEALER, '렉서스', ''), '토요타', '') \n "
			 +", DEALER_CD\n "
			 +", TFSKR_SALES_REP\n "
			+"\n "
			 +", R.TARGET_CNT\n "
			 +", R.TARGET_AMT\n "
			 +", R.TARGET_MS\n "
			 +", R.CAR_SALES \n "
			 +", R.TFSKR_FUNDING \n "
			 +", R.MS_ALL\n "
			+"	 \n "
			 +"-- Applied\n "
			 +", TM_APPLIED  \n "
			 +"-- Approved \n "
			 +", TM_T_APPROVED\n "
			 +"-- ETC\n "
			 +", ETC = TM_PENDING + TM_CON_APPROVED + TM_REJECTED + TM_OTHERS\n "
			+"	 \n "
			+"	FROM (  \n "
			+"	SELECT KIJUN_DATE = @KIJUN_DATE\n "
			+"	/*\n "
			 +", BRAND = (SELECT CODE_HNAME  \n "
			   +"FROM LSBSOPE    \n "
			  +"WHERE CODE_FIRST = X.AT_CAR_KUBUN)\n "
			 +", BRAND_CD = X.AT_CAR_KUBUN  \n "
			+"*/ \n "
			 +", DEALER = ISNULL((SELECT DEALER_NAME   \n "
			+"FROM DFBSSAP   \n "
			   +"WHERE DEALER_CODE = X.CF_HCODE_DL), '합계')\n "
			 +", DEALER_CD = ISNULL(X.CF_HCODE_DL, 'TOT')\n "
			 +", ORDERS = ISNULL((SELECT DEALER_NAME   \n "
			+"FROM DFBSSAP   \n "
			   +"WHERE DEALER_CODE = X.CF_HCODE_DL), 'ZZZ')  \n "
			 +", TFSKR_SALES_REP = ISNULL((SELECT (SELECT USR_NAME\n "
						   +"FROM LSSMUSR\n "
						  +"WHERE TFSKR_SALES_REP = USR_IDNO\n "
						 +")  \n "
				+"FROM DFBSSAP   \n "
			   +"WHERE DEALER_CODE = X.CF_HCODE_DL), '')  \n "
				   +"\n "
			 +", TM_APPLIED = SUM(CASE WHEN TYPE = 'TM' THEN X.APPLIED ELSE 0 END) \n "
			+"	 \n "
			 +", TM_T_APPROVED = SUM(CASE WHEN TYPE = 'TM' THEN X.APPROVED + X.FUNDED ELSE 0 END) \n "
			+"	 \n "
			 +", TM_PENDING = SUM(CASE WHEN TYPE = 'TM' THEN X.PENDING ELSE 0 END) \n "
			 +", TM_CON_APPROVED = SUM(CASE WHEN TYPE = 'TM' THEN X.CON_APPROVED ELSE 0 END) \n "
			 +", TM_REJECTED = SUM(CASE WHEN TYPE = 'TM' THEN X.REJECTED ELSE 0 END) \n "
			 +", TM_OTHERS = SUM(CASE WHEN TYPE = 'TM' THEN X.OTHERS ELSE 0 END) \n "
			  +"\n "
			 +"FROM ( \n "
			+"/* This month   */  \n "
			+"SELECT 'SUM' = SUM(1) \n "
			  +", X.AT_CAR_KUBUN \n "
			  +", X.CF_HCODE_DL \n "
			  +", TYPE = 'TM' \n "
			  +", 'A_APPROVED' = SUM(CASE WHEN X.AUTO_APPROVAL = 'Y' THEN 1 ELSE 0 END) \n "
			  +", 'APPLIED' = SUM(1) \n "
			  +", 'FUNDED' = SUM(CASE WHEN X.KY_STATUS IN ('A461', 'A462', 'A463', 'A464', 'A468', 'A469') THEN 1 ELSE 0 END)  \n "
			  +", 'APPROVED' = SUM(CASE WHEN X.KY_STATUS = '심사(승인)' THEN 1 ELSE 0 END) \n "
			  +", 'PENDING' = SUM(CASE WHEN X.KY_STATUS = '심사(보류)' THEN 1 ELSE 0 END) \n "
			  +", 'CON_APPROVED' = SUM(CASE WHEN X.KY_STATUS = '심사(조건부심사)' THEN 1 ELSE 0 END) \n "
			  +", 'REJECTED' = SUM(CASE WHEN X.KY_STATUS = '심사(거절)' THEN 1 ELSE 0 END) \n "
			  +", 'OTHERS' = SUM(CASE WHEN X.KY_STATUS IN ('A4611') OR X.KY_STATUS IS NULL THEN 1 ELSE 0 END) \n "
			  +", X.KY_NO, X.SIL_COUNT \n "
			+"FROM ( \n "
			+"SELECT \n "
			  +"C.KY_NO , C.SIL_COUNT \n "
			+", C.AT_CAR_KUBUN \n "
			+", C.CF_HCODE_DL \n "
			+", C.MDEL_CD \n "
			+", C.PROD_TYPE \n "
			+", C.ENTRY_DATE \n "
			+", C.AUTO_APPROVAL \n "
			+", KY_STATUS = CASE WHEN C.SIL_DATE >= ISNULL(A.ENTRY_DATE, '') THEN \n "
			+"	   CASE WHEN C.KY_STATUS IN ('A46111' \n "
			 +",'A4612' \n "
			 +",'A4613' \n "
			 +",'A4614' \n "
			 +",'A4615' \n "
			 +",'A4616') \n "
			 +"THEN A.SUBJECT \n "
			 +"ELSE C.KY_STATUS \n "
			  +"END \n "
			+"	    \n "
			+"ELSE    \n "
			+"			CASE WHEN C.KY_STATUS = 'A461' THEN C.KY_STATUS    \n "
			 +"ELSE  \n "
			  +"A.SUBJECT    \n "
			 +"END 	\n "
			+"END     \n "
			+"FROM \n "
			+"		LSGMACT C \n "
			+"LEFT OUTER JOIN \n "
			+"MMSDATA A ON C.KY_NO = A.KY_NO AND C.SIL_COUNT = A.SIL_COUNT \n "
			  +"AND SUBSTRING(A.INTIME,1,8) <= @TO_DATE\n "
			+"		 AND SUBJECT IN ('심사(승인)', '심사(보류)', '심사(조건부심사)', '심사(거절)') \n "
			 +"AND A.RESULT = 'Y' \n "
			 +"AND A.BIZ_GUBN = 'CREDIT' \n "
			 +"AND A.SEQNO = ( \n "
			   +"SELECT SEQNO = MAX(SEQNO) \n "
			  +"FROM MMSDATA S \n "
			+"WHERE S.BIZ_GUBN = 'CREDIT' \n "
			   +"AND SUBSTRING(S.INTIME,1,8) <= @TO_DATE\n "
			   +"AND S.SUBJECT IN ('심사(승인)', '심사(보류)', '심사(조건부심사)', '심사(거절)') \n "
			   +"AND S.RESULT = 'Y' \n "
			   +"AND A.KY_NO = S.KY_NO \n "
			   +"AND A.SIL_COUNT = S.SIL_COUNT \n "
			+"GROUP BY KY_NO, SIL_COUNT \n "
			   +") \n "
			 +"WHERE 1=1 \n "
			   +"AND CONVERT(CHAR(8),C.ENTRY_DATE,112) BETWEEN SUBSTRING(@TO_DATE, 1,6) + '01' AND @TO_DATE \n "
			   +"AND SUBSTRING(C.KY_NO,2,1) <> 'R' AND SUBSTRING(C.KY_NO,2,1) <> 'T' \n "
			   +"AND LEFT(C.SIL_COUNT,1) = '0' AND RIGHT(C.SIL_COUNT,'1') = '1' \n "
			   +"AND SUBSTRING(C.KY_NO,2,1) <> 'D' /* 시승차제외 */  \n "
			   +"AND C.AT_CAR_KUBUN = @AT_CAR_KUBUN\n "
			   +"AND ISNULL(C.USEDCAR_GUBN,'B911') = 'B911' \n "
			+") X \n "
			+"WHERE 1=1 \n "
			+"GROUP BY X.AT_CAR_KUBUN, X.CF_HCODE_DL, X.KY_NO, X.SIL_COUNT, X.MDEL_CD, X.PROD_TYPE\n "
			+"	   \n "
			+"	) X \n "
			+"	GROUP BY X.CF_HCODE_DL WITH ROLLUP  \n "
			+"	) Z   \n "
			 +"-- SALES REPORT에서 가져옴. START\n "
			+"LEFT OUTER JOIN\n "
			+"(\n "
			+"SELECT 				\n "
			 +"DEALER_NAME = ISNULL(S.DEALER_NAME, 'TOT')\n "
			+", TARGET_CNT = CASE WHEN @AT_CAR_KUBUN = 'A271' THEN\n "
			 +"CASE DEALER_NAME\n "
			 +"WHEN 'D000002' THEN 31\n "
			 +"WHEN 'D000031' THEN 23\n "
			 +"WHEN 'D000004' THEN 31\n "
			 +"WHEN 'D000005' THEN 27\n "
			 +"WHEN 'D000006' THEN 21\n "
			 +"WHEN 'D000007' THEN 9\n "
			 +"WHEN 'D000008' THEN 11\n "
			 +"WHEN 'D000009' THEN 16\n "
			 +"WHEN 'D000010' THEN 5	\n "
			 +"ELSE 174\n "
			 +"END						\n "
			+"ELSE\n "
			+"							CASE DEALER_NAME\n "
			 +"WHEN 'D000015' THEN 12\n "
			 +"WHEN 'D000016' THEN 10\n "
			 +"WHEN 'D000017' THEN 12\n "
			 +"WHEN 'D000018' THEN 12\n "
			 +"WHEN 'D000019' THEN 12\n "
			 +"WHEN 'D000023' THEN 3\n "
			 +"WHEN 'D000029' THEN 7\n "
			 +"WHEN 'D000021' THEN 9\n "
			 +"WHEN 'D000026' THEN 3	\n "
			 +"ELSE 80\n "
			 +"END\n "
			+"END					 	   \n "
			+"				 	    \n "
			+", TARGET_AMT = CASE WHEN @AT_CAR_KUBUN = 'A271' THEN\n "
			 +"CASE DEALER_NAME\n "
			+"WHEN	'D000002'	THEN 1614\n "
			+"WHEN	'D000031'	THEN 1258\n "
			+"WHEN	'D000004'	THEN 1523\n "
			+"WHEN	'D000005'	THEN 1269\n "
			+"WHEN	'D000008'	THEN 584\n "
			+"WHEN	'D000006'	THEN 1040\n "
			+"WHEN	'D000009'	THEN 886\n "
			+"WHEN	'D000007'	THEN 507\n "
			+"WHEN	'D000010'	THEN 189\n "
			+"ELSE	8870\n "
			+"END\n "
			+"ELSE\n "
			+"							CASE DEALER_NAME\n "
			 +"WHEN 'D000015' THEN 12\n "
			 +"WHEN 'D000016' THEN 10\n "
			 +"WHEN 'D000017' THEN 12\n "
			 +"WHEN 'D000018' THEN 12\n "
			 +"WHEN 'D000019' THEN 12\n "
			 +"WHEN 'D000023' THEN 3\n "
			 +"WHEN 'D000029' THEN 7\n "
			 +"WHEN 'D000021' THEN 9\n "
			 +"WHEN 'D000026' THEN 3	\n "
			 +"ELSE 80\n "
			 +"END\n "
			+"END\n "
			+"		\n "
			+", TARGET_MS = CASE WHEN @AT_CAR_KUBUN = 'A271' THEN\n "
			 +"CASE DEALER_NAME\n "
			+"WHEN	'D000002'	THEN	'31.00'\n "
			+"WHEN	'D000031'	THEN	'26.70'\n "
			+"WHEN	'D000004'	THEN	'34.80'\n "
			+"WHEN	'D000005'	THEN	'30.30'\n "
			+"WHEN	'D000008'	THEN	'31.40'\n "
			+"WHEN	'D000006'	THEN	'30.90'\n "
			+"WHEN	'D000009'	THEN	'30.80'\n "
			+"WHEN	'D000007'	THEN	'27.30'\n "
			+"WHEN	'D000010'	THEN	'17.90'\n "
			+"ELSE	'30.00'\n "
			+"END\n "
			+"ELSE\n "
			+"							CASE DEALER_NAME\n "
			 +"WHEN 'D000015' THEN '12'\n "
			 +"WHEN 'D000016' THEN '10'\n "
			 +"WHEN 'D000017' THEN '12'\n "
			 +"WHEN 'D000018' THEN '12'\n "
			 +"WHEN 'D000019' THEN '12'\n "
			 +"WHEN 'D000023' THEN '3'\n "
			 +"WHEN 'D000029' THEN '7'\n "
			 +"WHEN 'D000021' THEN '9'\n "
			 +"WHEN 'D000026' THEN '3'\n "
			 +"ELSE '80'\n "
			 +"END\n "
			+"END								 	    			\n "
						 	    									+"\n "
			  +",CAR_SALES  = SUM(CHK_1)+ SUM(CHK_2)   \n "
			  +",TFSKR_FUNDING = CASE WHEN S.DEALER_NAME IS NULL THEN\n "
			+"(SELECT COUNT(*) \n "
			  +"FROM LSGMACT A \n "
			 +"WHERE ( A.KY_STATUS = 'A461' OR A.KY_STATUS = 'A469'  OR A.KY_STATUS = 'A463'  OR A.KY_STATUS = 'A464' )  \n "
			   +"AND CONVERT(CHAR(8),SIL_DATE,112) BETWEEN @FROM_DATE AND @TO_DATE \n "
			   +"AND RIGHT(A.SIL_COUNT,1) = '1' \n "
			   +"AND LEFT(A.SIL_COUNT,1) = '0' \n "
			   +"AND A.AT_CAR_KUBUN = @AT_CAR_KUBUN\n "
			   +"AND ISNULL(A.USEDCAR_GUBN,'B911') = 'B911' \n "
			   +")\n "
			+"ELSE\n "
			+"(SELECT COUNT(*) \n "
			  +"FROM LSGMACT A \n "
			 +"WHERE ( A.KY_STATUS = 'A461' OR A.KY_STATUS = 'A469'  OR A.KY_STATUS = 'A463'  OR A.KY_STATUS = 'A464' )  \n "
			   +"AND CONVERT(CHAR(8),SIL_DATE,112) BETWEEN @FROM_DATE AND @TO_DATE \n "
			   +"AND RIGHT(A.SIL_COUNT,1) = '1' \n "
			   +"AND LEFT(A.SIL_COUNT,1) = '0' \n "
			   +"AND ISNULL(A.USEDCAR_GUBN,'B911') = 'B911'\n "
			   +"AND CF_HCODE_DL = S.DEALER_NAME )\n "
			+"END   \n "
			  +",MS_ALL = CONVERT(NUMERIC(18,1),CONVERT(NUMERIC(18,1),(\n "
			+"CASE WHEN S.DEALER_NAME IS NULL THEN \n "
			+"(SELECT COUNT(*) \n "
			+"				   FROM LSGMACT A \n "
			  +"WHERE ( A.KY_STATUS = 'A461' OR A.KY_STATUS = 'A469' OR A.KY_STATUS = 'A463' OR A.KY_STATUS = 'A464')\n "
			+"AND CONVERT(CHAR(8),SIL_DATE,112) BETWEEN @FROM_DATE AND @TO_DATE \n "
			+"AND RIGHT(A.SIL_COUNT,1) = '1' \n "
			+"AND LEFT(A.SIL_COUNT,1) = '0'\n "
			+"AND ISNULL(A.USEDCAR_GUBN,'B911') = 'B911'\n "
			+"AND A.AT_CAR_KUBUN = @AT_CAR_KUBUN )\n "
			+"ELSE\n "
			+"(SELECT COUNT(*) \n "
			   +"FROM LSGMACT A \n "
			  +"WHERE ( A.KY_STATUS = 'A461' OR A.KY_STATUS = 'A469' OR A.KY_STATUS = 'A463' OR A.KY_STATUS = 'A464')\n "
			+"AND CONVERT(CHAR(8),SIL_DATE,112) BETWEEN @FROM_DATE AND @TO_DATE \n "
			+"AND RIGHT(A.SIL_COUNT,1) = '1' \n "
			+"AND LEFT(A.SIL_COUNT,1) = '0' \n "
			+"AND ISNULL(A.USEDCAR_GUBN,'B911') = 'B911'\n "
			+"AND CF_HCODE_DL = S.DEALER_NAME )\n "
			+"END\n "
			+"))\n "
			+"/  CONVERT(NUMERIC(18,1),SUM(CHK_1)+ SUM(CHK_2)) * 100)\n "
			 +"FROM (SELECT  DEALER_NAME, VEHICLE_MODEL, VIN, VEHICLE_TYPE, SALES_DATE, AT_CAR_KUBUN\n "
			 +",CHK_1 =  (CASE WHEN VEHICLE_TYPE NOT IN ('TEST VEHICLE','TEST USED VEHICLE') THEN 1 ELSE 0 END) \n "
			 +",CHK_2 =  (CASE WHEN VEHICLE_TYPE IN ('TEST VEHICLE','TEST USED VEHICLE') THEN 1 ELSE 0 END) \n "
			 +"FROM  LSGMSAR WHERE SALES_DATE BETWEEN @FROM_DATE AND @TO_DATE  AND AT_CAR_KUBUN = @AT_CAR_KUBUN\n "
			 +"GROUP BY  DEALER_NAME, VEHICLE_MODEL, VIN, VEHICLE_TYPE, SALES_DATE, AT_CAR_KUBUN) S \n "
			 +"GROUP BY S.DEALER_NAME WITH ROLLUP\n "
			 +") AS R ON Z.DEALER_CD = R.DEALER_NAME\n "
			+"-- SALES REPORT에서 가져옴. END\n "
			+"\n "
			+"	WHERE 1=1\n "
			  +"--AND ((Z.BRAND IS NOT NULL AND Z.ORDERS != 'ZZZ') \n "
			  +"-- OR (Z.BRAND IS  NULL AND Z.ORDERS = 'ZZZ')) \n "
			+"--  and DEALER_CD in ('D000002','D000004','D000005','D000007','D000008')\n "
			+"\n "
			+"	ORDER BY CASE WHEN @AT_CAR_KUBUN = 'A271' THEN\n "
			+"	(CASE WHEN DEALER_CD = 'D000002' THEN '01'\n "
			+"WHEN DEALER_CD = 'D000003' THEN '02'   \n "
			+"WHEN DEALER_CD = 'D000031' THEN '03'   \n "
			+"WHEN DEALER_CD = 'D000004' THEN '04'   \n "
			+"WHEN DEALER_CD = 'D000005' THEN '05'   \n "
			+"WHEN DEALER_CD = 'D000006' THEN '06'   \n "
			+"WHEN DEALER_CD = 'D000007' THEN '07'   \n "
			+"WHEN DEALER_CD = 'D000008' THEN '08'   \n "
			+"WHEN DEALER_CD = 'D000009' THEN '09'   \n "
			+"WHEN DEALER_CD = 'D000010' THEN '10'   \n "
			+"ELSE '99'                                  \n "
			+"END)   \n "
			+"			\n "
			+"\n "
			+"	ELSE\n "
			+"	(CASE WHEN DEALER_CD = 'D000015' THEN '01'\n "
			+"WHEN DEALER_CD = 'D000016' THEN '02'   \n "
			+"WHEN DEALER_CD = 'D000017' THEN '03'   \n "
			+"WHEN DEALER_CD = 'D000018' THEN '04'   \n "
			+"WHEN DEALER_CD = 'D000019' THEN '05'   \n "
			+"WHEN DEALER_CD = 'D000023' THEN '06'   \n "
			+"WHEN DEALER_CD = 'D000029' THEN '07'   \n "
			+"WHEN DEALER_CD = 'D000021' THEN '08'   \n "
			+"WHEN DEALER_CD = 'D000026' THEN '09'\n "
			+"ELSE '99'                                  \n "
			+"END)  \n "
			+"END\n "
			+"END\n ";
		return mySQL;
	}
	
	
	
	
	
	
	
}
